import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { apiGet, apiList, apiPatch, apiPost } from "../api";
import { formatCreate, formatError, formatList, formatShow, formatUpdate, type EduframeRecord } from "../formatters";
import { logResponse } from "../response-logger";

export function registerAccountTools(server: McpServer): void {
  server.registerTool(
    "get_accounts",
    {
      description: "Get all accounts",
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      inputSchema: {
        cursor: z.string().optional().describe("Cursor for fetching the next page of results"),
        per_page: z.number().int().positive().optional().describe("Number of results per page (default: 25)"),
        search: z.string().optional().describe("Filter results on search"),
        key_contact_user_id: z.number().int().optional().describe("Filter results on key_contact_user_id"),
        user_id: z.number().int().optional().describe("Filter results on user_id"),
        account_type: z.enum(["business", "personal"]).optional().describe("Filter results on account_type"),
      },
    },
    async ({ cursor, per_page, search, key_contact_user_id, user_id, account_type }) => {
      try {
        const result = await apiList<EduframeRecord>("/accounts", {
          cursor,
          per_page,
          search,
          key_contact_user_id,
          user_id,
          account_type,
        });
        void logResponse(
          "get_accounts",
          { cursor, per_page, search, key_contact_user_id, user_id, account_type },
          result,
        );
        const toolResult = formatList(result.records, "accounts");
        if (result.nextCursor) {
          toolResult.content.push({ type: "text", text: `\nNext page cursor: ${result.nextCursor}` });
        }
        return toolResult;
      } catch (error) {
        return formatError(error);
      }
    },
  );

  server.registerTool(
    "get_account",
    {
      description: "Get a single account",
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      inputSchema: { id: z.number().int().positive().describe("ID of the account to retrieve") },
    },
    async ({ id }) => {
      try {
        const record = await apiGet<EduframeRecord>(`/accounts/${id}`);
        void logResponse("get_account", { id }, record);
        return formatShow(record, "account");
      } catch (error) {
        return formatError(error);
      }
    },
  );

  server.registerTool(
    "create_account",
    {
      description: "Create an account",
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
      inputSchema: {
        name: z
          .string()
          .describe("Arbitrary string representing the name of the account. Is autogenerated for personal accounts."),
        email: z.string().optional().describe("A string representing the billing e-mail of the account"),
        phone: z.string().optional().describe("A string representing the phone number of the account"),
        label_ids: z.array(z.number().int()).optional().describe("IDs of the labels"),
        custom: z.object({}).optional().describe("The custom properties of the account."),
        address_attributes: z
          .object({
            addressee: z.string().optional().describe("The addressee of the address."),
            address: z.string().describe("Concatenation of the street and house number."),
            address_line2: z.string().optional().describe("A string representing the second line of the address."),
            postal_code: z.string().describe("A string representing the postal code."),
            city: z.string().describe("A string representing the city."),
            state_province: z.string().optional().describe("An letter USA state code."),
            country: z.string().describe("An ISO3166 two-letter country code."),
          })
          .optional(),
        signup_answers_attributes: z
          .array(
            z.object({
              signup_question_id: z.number().int().describe("Unique identifier of the question."),
              value: z
                .union([z.string(), z.boolean(), z.array(z.string())])
                .describe("The formatted value of the answer."),
            }),
          )
          .optional(),
      },
    },
    async (body) => {
      try {
        const record = await apiPost<EduframeRecord>("/accounts", body);
        void logResponse("create_account", body, record);
        return formatCreate(record, "account");
      } catch (error) {
        return formatError(error);
      }
    },
  );

  server.registerTool(
    "update_account",
    {
      description: "Update an account",
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
      inputSchema: {
        id: z.number().int().positive().describe("ID of the account to update"),
        name: z
          .string()
          .describe("Arbitrary string representing the name of the account. Is autogenerated for personal accounts."),
        email: z.string().optional().describe("A string representing the billing e-mail of the account"),
        phone: z.string().optional().describe("A string representing the phone number of the account"),
        label_ids: z.array(z.number().int()).optional().describe("IDs of the labels"),
        custom: z.object({}).optional().describe("The custom properties of the account."),
        address_attributes: z
          .object({
            addressee: z.string().optional().describe("The addressee of the address."),
            address: z.string().describe("Concatenation of the street and house number."),
            address_line2: z.string().optional().describe("A string representing the second line of the address."),
            postal_code: z.string().describe("A string representing the postal code."),
            city: z.string().describe("A string representing the city."),
            state_province: z.string().optional().describe("An letter USA state code."),
            country: z.string().describe("An ISO3166 two-letter country code."),
          })
          .optional(),
      },
    },
    async ({ id, ...body }) => {
      try {
        const record = await apiPatch<EduframeRecord>(`/accounts/${id}`, body);
        void logResponse("update_account", { id, ...body }, record);
        return formatUpdate(record, "account");
      } catch (error) {
        return formatError(error);
      }
    },
  );
}
